config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :spams
  match 'model/:model_name', via: [:get], controller: 'models', action: 'model_info'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spam.rb
# == Schema Information
#
# Table name: spams
#
#  id         :integer          not null, primary key
#  eggs       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Spam < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  admin      :boolean
#  bio        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord

  validates :first_name,
            presence: true

  validates :last_name,
            presence: { message: 'you need to give us a last name!' }

  validates :email,
            presence: {message: 'please provide an email'}

  validates :bio,
            presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController

  ##
  # params:
  #   model_name: exact name of model
  # return model info as json.
  #   col_name: the name of the column
  #   type: the AR datatype of the column
  #   validators: object. can contain any of the following
  #     acceptance
  #     confirmation:
  #     exclusion:
  #     format:
  #     inclusion:
  #     length:
  #     numericality:
  #     presence:
  #     absence:

  #   example:
  #   validators:
  #      presence:
  #         active: true
  #         message: "can't be blank"

  #     
  #     
  # Assumptions
  #   for now doesn't handle any validations that require a database call
  #      

  def model_info
    @model = params[:model_name].constantize
    column_data = @model.columns.map{|c| {col_name: c.name,
                                         type: c.sql_type_metadata.type,
                                         validators: assemble_validator_info(c.name)
                                        }
                                   }

    render json: {data: column_data}
  end

  private

  ## 
  # packages up all validation info on a column
  # col_name(string) name of a column
  # returns an array of hashs shaped like so:
  #   [
  #      {type: "presence", message: "can't be blank"}
  #      {type: "length", message: "some custom message"}
  #   ]
  def assemble_validator_info col_name
    validators = @model.validators_on(col_name).map do |validator|
      re = /ActiveRecord::Validations::(?<validator>.+)Validator/
      val_name = re.match(validator.class.to_s)['validator'].downcase
      {name: val_name, options: validator.options}
    end
    validators
  end

end

app/controllers/spams_controller.rb
class SpamsController < ApplicationController
  before_action :set_spam, only: [:show, :edit, :update, :destroy]

  # GET /spams
  # GET /spams.json
  def index
    puts 'hello from index controller'
    @spams = Spam.all
  end

  # GET /spams/1
  # GET /spams/1.json
  def show
  end

  # GET /spams/new
  def new
    @spam = Spam.new
  end

  # GET /spams/1/edit
  def edit
  end

  # POST /spams
  # POST /spams.json
  def create
    @spam = Spam.new(spam_params)

    respond_to do |format|
      if @spam.save
        format.html { redirect_to @spam, notice: 'Spam was successfully created.' }
        format.json { render :show, status: :created, location: @spam }
      else
        format.html { render :new }
        format.json { render json: @spam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spams/1
  # PATCH/PUT /spams/1.json
  def update
    respond_to do |format|
      if @spam.update(spam_params)
        format.html { redirect_to @spam, notice: 'Spam was successfully updated.' }
        format.json { render :show, status: :ok, location: @spam }
      else
        format.html { render :edit }
        format.json { render json: @spam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spams/1
  # DELETE /spams/1.json
  def destroy
    @spam.destroy
    respond_to do |format|
      format.html { redirect_to spams_url, notice: 'Spam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spam
      @spam = Spam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spam_params
      params.fetch(:spam, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/spams_helper.rb
module SpamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ArForms
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Latest compiled and minified CSS
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css", :rel => "stylesheet"}/
    / Optional theme
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css", :rel => "stylesheet"}/

  %body
    = yield

app/views/spams/_form.html.haml
= form_for @spam do |f|
  - if @spam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@spam.errors.count, "error")} prohibited this spam from being saved:"
      %ul
        - @spam.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/spams/edit.html.haml
%h1 Editing spam

= render 'form'

= link_to 'Show', @spam
\|
= link_to 'Back', spams_path

app/views/spams/index.haml
= javascript_pack_tag 'application'

app/views/spams/new.html.haml
%h1 New spam

= render 'form'

= link_to 'Back', spams_path

app/views/spams/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_spam_path(@spam)
\|
= link_to 'Back', spams_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path